version: "3.8"

services:
    pinecone:
        image: ghcr.io/pinecone-io/pinecone-local:latest
        environment:
            - PORT=5080
            - PINECONE_HOST=localhost
        ports:
            - "5080-5090:5080-5090"
        volumes:
            - pinecone-data:/data

    localstack:
        image: localstack/localstack
        ports:
            - "4566:4566"
            - "4510-4559:4510-4559"
        environment:
            - DEBUG=${DEBUG:-0}
        volumes:
            - ./localstack:/var/lib/localstack

    meilisearch:
        image: getmeili/meilisearch:v1.16
        ports:
            - "7700:7700"
        environment:
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
            - MEILI_ENV=development
        volumes:
            - meili_data:/meili_data

volumes:
    pinecone-data:
    meili_data:
