<?php

return [
    'skills' => [
        // Film & Animation
        ['value' => 'sinematografi', 'label' => 'Sinematografi'],
        ['value' => 'editing_video', 'label' => 'Editing Video'],
        ['value' => 'adobe_premiere', 'label' => 'Adobe Premiere'],
        ['value' => 'after_effects', 'label' => 'After Effects'],
        ['value' => 'animasi_2d', 'label' => 'Animasi 2D'],
        ['value' => 'character_design', 'label' => 'Character Design'],
        ['value' => 'toon_boom', 'label' => 'Toon Boom'],
        ['value' => 'adobe_animate', 'label' => 'Adobe Animate'],
        ['value' => 'motion_graphics', 'label' => 'Motion Graphics'],
        ['value' => 'cinema_4d', 'label' => 'Cinema 4D'],
        ['value' => 'blender', 'label' => 'Blender'],

        // Music & Audio
        ['value' => 'produksi_musik', 'label' => 'Produksi Musik'],
        ['value' => 'mixing', 'label' => 'Mixing'],
        ['value' => 'mastering', 'label' => 'Mastering'],
        ['value' => 'ableton_live', 'label' => 'Ableton Live'],
        ['value' => 'komposisi', 'label' => 'Komposisi'],
        ['value' => 'piano', 'label' => 'Piano'],
        ['value' => 'orchestration', 'label' => 'Orchestration'],
        ['value' => 'logic_pro', 'label' => 'Logic Pro'],
        ['value' => 'sound_design', 'label' => 'Sound Design'],
        ['value' => 'audio_engineering', 'label' => 'Audio Engineering'],
        ['value' => 'pro_tools', 'label' => 'Pro Tools'],
        ['value' => 'field_recording', 'label' => 'Field Recording'],

        // Fashion & Textile
        ['value' => 'fashion_design', 'label' => 'Fashion Design'],
        ['value' => 'pattern_making', 'label' => 'Pattern Making'],
        ['value' => 'adobe_illustrator', 'label' => 'Adobe Illustrator'],
        ['value' => 'sustainable_fashion', 'label' => 'Sustainable Fashion'],
        ['value' => 'fashion_styling', 'label' => 'Fashion Styling'],
        ['value' => 'photography_direction', 'label' => 'Photography Direction'],
        ['value' => 'trend_analysis', 'label' => 'Trend Analysis'],
        ['value' => 'wardrobe_consulting', 'label' => 'Wardrobe Consulting'],
        ['value' => 'textile_design', 'label' => 'Textile Design'],
        ['value' => 'batik', 'label' => 'Batik'],
        ['value' => 'natural_dyeing', 'label' => 'Natural Dyeing'],
        ['value' => 'weaving', 'label' => 'Weaving'],

        // Crafts (Kriya)
        ['value' => 'wood_carving', 'label' => 'Wood Carving'],
        ['value' => 'furniture_design', 'label' => 'Furniture Design'],
        ['value' => 'product_design', 'label' => 'Product Design'],
        ['value' => 'cnc_operation', 'label' => 'CNC Operation'],
        ['value' => 'keramik', 'label' => 'Keramik'],
        ['value' => 'pottery', 'label' => 'Pottery'],
        ['value' => 'glazing', 'label' => 'Glazing'],
        ['value' => 'sculpture', 'label' => 'Sculpture'],
        ['value' => 'metal_craft', 'label' => 'Metal Craft'],
        ['value' => 'jewelry_design', 'label' => 'Jewelry Design'],
        ['value' => 'silver_working', 'label' => 'Silver Working'],
        ['value' => 'bronze_casting', 'label' => 'Bronze Casting'],

        // Culinary Arts
        ['value' => 'indonesian_cuisine', 'label' => 'Indonesian Cuisine'],
        ['value' => 'menu_development', 'label' => 'Menu Development'],
        ['value' => 'food_photography', 'label' => 'Food Photography'],
        ['value' => 'restaurant_management', 'label' => 'Restaurant Management'],
        ['value' => 'baking', 'label' => 'Baking'],
        ['value' => 'pastry', 'label' => 'Pastry'],
        ['value' => 'cake_design', 'label' => 'Cake Design'],
        ['value' => 'food_styling', 'label' => 'Food Styling'],
        ['value' => 'barista', 'label' => 'Barista'],
        ['value' => 'coffee_roasting', 'label' => 'Coffee Roasting'],
        ['value' => 'latte_art', 'label' => 'Latte Art'],
        ['value' => 'beverage_innovation', 'label' => 'Beverage Innovation'],

        // Apps & Games Development
        ['value' => 'flutter', 'label' => 'Flutter'],
        ['value' => 'react_native', 'label' => 'React Native'],
        ['value' => 'ui_ux_design', 'label' => 'UI/UX Design'],
        ['value' => 'firebase', 'label' => 'Firebase'],
        ['value' => 'unity', 'label' => 'Unity'],
        ['value' => 'csharp', 'label' => 'C#'],
        ['value' => 'game_design', 'label' => 'Game Design'],
        ['value' => '2d_art', 'label' => '2D Art'],
        ['value' => 'laravel', 'label' => 'Laravel'],
        ['value' => 'vue_js', 'label' => 'Vue.js'],
        ['value' => 'mysql', 'label' => 'MySQL'],
        ['value' => 'aws', 'label' => 'AWS'],

        // Additional Skills
        ['value' => 'graphic_design', 'label' => 'Graphic Design'],
        ['value' => 'branding', 'label' => 'Branding'],
        ['value' => 'adobe_creative_suite', 'label' => 'Adobe Creative Suite'],
        ['value' => 'print_design', 'label' => 'Print Design'],
        ['value' => 'photography', 'label' => 'Photography'],
        ['value' => 'product_photography', 'label' => 'Product Photography'],
        ['value' => 'portrait', 'label' => 'Portrait'],
        ['value' => 'lightroom', 'label' => 'Lightroom'],
        ['value' => 'content_writing', 'label' => 'Content Writing'],
        ['value' => 'seo', 'label' => 'SEO'],
        ['value' => 'social_media', 'label' => 'Social Media'],
        ['value' => 'copywriting', 'label' => 'Copywriting'],
    ],

    'categories' => [
        ['value' => 'film_animasi', 'label' => 'Film & Animasi'],
        ['value' => 'musik', 'label' => 'Musik'],
        ['value' => 'fashion', 'label' => 'Fashion'],
        ['value' => 'kriya', 'label' => 'Kriya'],
        ['value' => 'kuliner', 'label' => 'Kuliner'],
        ['value' => 'aplikasi_game', 'label' => 'Aplikasi & Game'],
        ['value' => 'desain_grafis', 'label' => 'Desain Grafis'],
        ['value' => 'fotografi', 'label' => 'Fotografi'],
        ['value' => 'konten_digital', 'label' => 'Konten Digital'],
    ],

    'indonesian_cities' => [
        ['value' => 'jakarta', 'label' => 'Jakarta'],
        ['value' => 'bandung', 'label' => 'Bandung'],
        ['value' => 'surabaya', 'label' => 'Surabaya'],
        ['value' => 'yogyakarta', 'label' => 'Yogyakarta'],
        ['value' => 'semarang', 'label' => 'Semarang'],
        ['value' => 'medan', 'label' => 'Medan'],
        ['value' => 'makassar', 'label' => 'Makassar'],
        ['value' => 'denpasar', 'label' => 'Denpasar'],
        ['value' => 'palembang', 'label' => 'Palembang'],
        ['value' => 'samarinda', 'label' => 'Samarinda'],
        ['value' => 'batam', 'label' => 'Batam'],
        ['value' => 'balikpapan', 'label' => 'Balikpapan'],
    ],

    'creative_industries' => [
        ['value' => 'digital_agency', 'label' => 'Digital Agency'],
        ['value' => 'production_house', 'label' => 'Production House'],
        ['value' => 'fashion_brand', 'label' => 'Fashion Brand'],
        ['value' => 'gaming_studio', 'label' => 'Gaming Studio'],
        ['value' => 'advertising_agency', 'label' => 'Advertising Agency'],
        ['value' => 'media_publisher', 'label' => 'Media Publisher'],
        ['value' => 'e_commerce_platform', 'label' => 'E-commerce Platform'],
        ['value' => 'fintech_startup', 'label' => 'Fintech Startup'],
        ['value' => 'food_beverage', 'label' => 'Food & Beverage'],
        ['value' => 'travel_hospitality', 'label' => 'Travel & Hospitality'],
        ['value' => 'education_technology', 'label' => 'Education Technology'],
        ['value' => 'healthcare_digital', 'label' => 'Healthcare Digital'],
    ],
];
